site_name: ChromeCollateral
repo_url: https://github.com/FantasticRo/ChromeCollateral
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
nav:
  - Home: index.md
