site_name: Chrome & Collateral
repo_url: https://github.com/FantasticRo/ChromeCollateral
edit_uri: ""
theme:
  name: lux
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
nav:
  - Home: index.md
  - Guides:
      - Week Ending 8-24: guides/shortcuts.md
      - Workflows: guides/workflows.md
  - KB:
      - CLI: KB/cli.md
      - API: KB/api.md