nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Setup: getting-started/setup.md
  - Guides:
      - Shortcuts: guides/shortcuts.md
      - Workflows: guides/workflows.md
  - Reference:
      - CLI: reference/cli.md
      - API: reference/api.md
